site_name: Cluster.dev
# Page tree
repo_name: 'shalb/cluster.dev'
repo_url: 'https://github.com/shalb/cluster.dev'
site_url: 'https://cluster.dev'


nav:
  - Home:
    - Welcome: index.md
    - Concept:
      - Common infrastructure project structure: common-infra-project-structure.md
    - Install:
      - Prerequisites: prerequisites.md
      - Download from release: download-from-release.md
      - Build from source: build-from-source.md
  - Cloud Providers:
    - AWS: aws-cloud-provider.md
    - Google Cloud: google-cloud-provider.md
    - Azure: azure-cloud-provider.md
    - DigitalOcean: digital-ocean-cloud-provider.md
  - Quick Start: quick-start.md
  - Configuration:
    - Options List for Cluster Manifests: OPTIONS.md
  - Reference:
    - CLI commands: cli-commands.md
    - CLI options: cli-options.md
  - Releases:
    - Roadmap: ROADMAP.md


markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.tilde
  - toc:
      permalink: ' ¶'
theme:
  name: 'material'
  custom_dir: docs/theme-overrides
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true
  language: en
  features:
    - navigation.tabs
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  logo: '/images/cluster-dev-logo-small-white.png'
  favicon: 'images/favicon.png'
google_analytics:
  - UA-157259461-1
  - auto
extra:
  social:
    - icon: fontawesome/brands/slack
      link: https://join.slack.com/t/cluster-dev/shared_invite/zt-eg4q6jae-v0~zgrBLYTTXt~CjnjmprA
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/shalbcom
    - icon: fontawesome/brands/github
      link: https://github.com/shalb/cluster.dev
