name: Bin-release
on: 
  push:
    branches:
      - new-reconciler


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: golang:1.16.0-alpine
    steps:

    - name: Install make
      run: apk add make bash jq curl git

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Build
      run: |
        git fetch --prune --unshallow --tags
        git describe --tags
      env:
        CGO_ENABLED: 0


